### PR TITLE
Fixing installation issue that made KaSaAn.core unavailable

### PR DESCRIPTION
**Pull request by yarden**
Edited ``setup.py`` so that ``KaSaAn.core`` can be exposed to users.

### CODE REVIEW

**Comment by yarden** [comment]
This should fix https://github.com/hmedina/KaSaAn/issues/3

**Comment by hmedina** [comment]
Are these the commits you intended? a140bb2 removes the strict Python3.7 requirement removed in 47533cec9b86c3e2515351a859df7aa7fcc438b5, and 4473cb6 updates the requirements as done in 22c8933ea11c77b1bfed26e27a280d4da99d08ff ; these commits update parts of the file to a state already present in the master branch.

**Comment by yarden** [comment]
Arg, those were wrong commits, the only relevant thing is making ``packages`` into this:

```
    packages=['KaSaAn', 'KaSaAn.core'],
```

**Comment by hmedina** [comment]
Ok, that's what I included in the latest fix, so it should be good now.

**Pull request closed without merging**
